### ISSUE TITLE
rn新人，运行下载的项目，出现错误提示，求大佬指点！

### ISSUE THREAD

**Issue by mhl888** [reactnativecn/react-native-website#133]
提示错误信息为：
bundling failed: Error: Unable to resolve module `react-native/Libraries/Pressability/Pressability.js` from `node_modules\teaset\components\ListRow\TouchableOpacity.js`: react-native/Libraries/Pressability/Pressability.js could not be found within the project.
If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at dependencies.map.result (D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\MyPro\MyPro2\teaset-master\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

**Comment by sunnylqm** [comment]
https://github.com/rilyu/teaset/issues/422

**Comment by mhl888** [comment]
> [琉球/茶具＃422](https://github.com/rilyu/teaset/issues/422)
根据您的引导我使用了teaset-0.7.4，但还是出现了和之前一样的错误提示信息诶，我的版本是0.61.5

**Comment by sunnylqm** [comment]
1. 人家的说明是需要0.7.1，不是0.7.4
2. 第三方的问题请去第三方的仓库里提问和跟进

**Comment by huxiaoqiao** [comment]
@mhl888 哥们，后来怎么解决的？
