### ISSUE TITLE
yarn react-native run-android运行出错

### ISSUE THREAD

**Issue by KidUncle** [reactnativecn/react-native-website#160]
以下是报错信息：
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)  
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)       
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:606)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
        at org.gradle.wrapper.Download.download(Download.java:52)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:606)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
        at org.gradle.wrapper.Download.download(Download.java:52)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

    at makeError (D:\AwesomeProject\node_modules\execa\index.js:174:9)
    at D:\AwesomeProject\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (D:\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\AwesomeProject\node_modules\@react-native-community\cli\build\index.js:186:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sunnylqm** [comment]
翻墙问题

**Comment by KidUncle** [comment]
我试了浏览youtube没什么太大压力，而且android studio也配置成功了

**Comment by sunnylqm** [comment]
检查下配置，不一定命令行能翻墙

**Comment by KidUncle** [comment]
主要是下载这个gradle报的错Downloading https://services.gradle.org/distributions/gradle-6.0.1-all.zip，我点击这个链接，可以手动下载。

**Comment by sunnylqm** [comment]
你点击这个链接就跳到浏览器去了，浏览器能下载不代表命令行能下载
这个手动下载也可以，和gradle-wrapper.properties放在一起，然后修改里面的网址改成本地文件名即可

**Comment by KidUncle** [comment]
我把grdle的包zip放在gardle/wrapper下，重新 命令行: yarn react-native run-android，依然报同样的错误，是需要在android studio中打开此项目？

**Comment by KidUncle** [comment]
我把grdle-6.0.1-all.zip以及解压后的的包都放在user/.gradle里面了，然后在yarn android 就可以运行了，然后又报新错误。

**Comment by KidUncle** [comment]
新错误如下
A problem occurred configuring root project 'AwesomeProject'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.2.
         > Could not get resource 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
               > Connect to maven.aliyun.com:443 [maven.aliyun.com/59.110.251.10, maven.aliyun.com/59.110.251.11, maven.aliyun.com/182.92.29.54, maven.aliyun.com/182.
92.29.16, maven.aliyun.com/59.110.251.4, maven.aliyun.com/182.92.29.53, maven.aliyun.com/59.110.251.9, maven.aliyun.com/59.110.251.12, maven.aliyun.com/182.92.29.13,
maven.aliyun.com/182.92.29.40] failed: Connection timed out: connect
      > Could not resolve com.android.tools.build:gradle:3.5.2.
         > Could not get resource 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
               > Connect to maven.aliyun.com:443 [maven.aliyun.com/182.92.29.54, maven.aliyun.com/182.92.29.53, maven.aliyun.com/182.92.29.40, maven.aliyun.com/182.92
.29.16, maven.aliyun.com/182.92.29.13, maven.aliyun.com/59.110.251.12, maven.aliyun.com/59.110.251.11, maven.aliyun.com/59.110.251.10, maven.aliyun.com/59.110.251.9,
maven.aliyun.com/59.110.251.4] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21m 22s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose
 flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

**Comment by sunnylqm** [comment]
还是一样的网络问题啊
说明你的代理设置有问题啊

**Comment by KidUncle** [comment]
明白了，果然是代理问题。谢谢你！
