### ISSUE TITLE
java.lang.SecurityException: Permission Denial: package=null does not belong to uid=2000

### ISSUE THREAD

**Issue by majiabin** [reactnativecn/react-native-website#243]
java.lang.SecurityException: Permission Denial: package=null does not belong to uid=2000
        at com.android.server.wm.ActivityTaskManagerService.assertPackageMatchesCallingUid(ActivityTaskManagerService.java:2555)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1078)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1067)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3584)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:518)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)
        at android.os.ShellCommand.exec(ShellCommand.java:111)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10107)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4727)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2814)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by explorefit** [comment]
遇到了同样的问题

**Comment by explorefit** [comment]
刚解决，使用的小米手机，更新手机系统后，可以正常启动
