### ISSUE TITLE
0.63.0及以上版本启动后出现红屏保错 Error: Unable to resolve module `./Libraries/YellowBox/YellowBox` from `node_modules\react-native\index.js` 

### ISSUE THREAD

**Issue by lirongNISL** [reactnativecn/react-native-website#267]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 如果是安装过程中的问题，请再三确认你有使用稳定的翻墙工具，且翻墙工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 请尽量配上相关报错截图
   - 如果设备上有红屏报错请直接截图
   - 如果命令行有报错请直接截图
   - 警告(warning)一般不用管
   - 如果设备上看不到报错，请先尝试[调试模式](https://reactnative.cn/docs/debugging)。
   - 如果是发行版本无法调试，对于安卓设备请使用[adb logcat命令](https://developer.android.google.cn/studio/command-line/logcat)来捕获日志并粘贴到这里。iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by sunnylqm** [comment]
yellowbox已经移除了，现在叫logbox

**Comment by lirongNISL** [comment]
好的，谢谢，在引用的地方删除即可对吧。可是install的时候选择的react-native@0.63.0了，删除了yellowbox，为什么下载的依赖代码里还会引用，很奇怪。

**Comment by sunnylqm** [comment]
什么叫下载的依赖代码里还会引用

**Comment by lirongNISL** [comment]
我的意思是既然已经删除了，npm install 的代码里还在引用yellowbox，install 版本react-native@0.63.0 ~0.63.3代码都会报上面的错误。目前手动去Libraries\ReactNative下删除yellowbox，依然报错

error: Error: Unable to resolve module `../YellowBox/YellowBox` from `node_modules\react-native\Libraries\ReactNative\AppContainer.js`:
None of these files exist:
  * node_modules\react-native\Libraries\YellowBox\YellowBox(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native\Libraries\YellowBox\YellowBox\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (D:\coding\RN_Project\Spark\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (D:\coding\RN_Project\Spark\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\coding\RN_Project\Spark\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (D:\coding\RN_Project\Spark\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at D:\coding\RN_Project\Spark\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (D:\coding\RN_Project\Spark\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at D:\coding\RN_Project\Spark\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\coding\RN_Project\Spark\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

**Comment by sunnylqm** [comment]
具体的引用代码在哪，我这里并没有看到

**Comment by mason-hz** [comment]
npx react-native start --reset-cache
