### ISSUE TITLE
执行yarn Android 报错

### ISSUE THREAD

**Issue by zhaoxigit** [reactnativecn/react-native-website#288]
执行yarn Android 报错

yarn android
yarn run v1.22.10
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 967 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...
Downloading https://services.gradle.org/distributions/gradle-6.2-all.zip
.........
Could not unzip C:\Users\zhaoxi\.gradle\wrapper\dists\gradle-6.2-all\dvufqs6kielxeao781pmk5huj\gradle-6.2-all.zip to C:\Users\zhaoxi\.gradle\wrapper\dists\gradle-6.2-all\dvufqs6kielxeao781pmk5
huj.
Reason: error in opening zip file
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:235)
        at org.gradle.wrapper.Install.access$900(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:81)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zhaoxigit** [comment]
反反复复安装卸载Android studio 和SDK好几次了 ，javac 也能正常执行，找不到原因
![image](https://user-images.githubusercontent.com/41280993/97280395-2ec88480-1877-11eb-9fab-6bca34f39f58.png)

**Comment by sunnylqm** [comment]
gradle下载失败
https://github.com/reactnativecn/react-native-website/issues/278#issuecomment-713454747

**Comment by zhaoxigit** [comment]
感谢：） 起来了
