### ISSUE TITLE
Android如何在未使用RN默认目录的情况下启用自动链接?

### ISSUE THREAD

**Issue by 322455116** [reactnativecn/react-native-website#403]
## android  RN自动链接相关问题.
 - 程序中未使用RN的默认目录.而是把RN放在了与APP平级的目录下面.目录结构如图.
 - 同一台机器经测试,无论是使用官方语法新建工程,或者按照将reactnative集成到现有项目这一文档将现有工程集成RN,不改变目录的情况下,自动链接均不会报错.
![image](https://user-images.githubusercontent.com/50320468/111743896-528f7400-88c5-11eb-8524-89eb17e15bb2.png)
可以成功运行react-native代码.
此时如果按照官方代码
```
apply from: file("../RNComps/node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); 
applyNativeModulesAppBuildGradle(project)
```
在setting.gradle中使用设置自动链接,会报错
```
Cause: internal/modules/cjs/loader.js:969
  throw err;  ^Error: Cannot find module 'react-native/cli'Require stack:- F:\unicorn_aged\[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15) 
   at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19) 
   at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:13
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38) 
   at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30) 
   at evalScript (internal/process/execution.js:94:25) 
{  code: 'MODULE_NOT_FOUND',  
requireStack: [ 'F:\\unicorn_aged\\[eval]' ]}

```
查阅资料后发现可能是native_modules.gradle读取到的android目录设置错误,请问如何解决这个错误?或者如何在react-native设置android的程序目录?谢谢!

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.48 GB / 15.84 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-S | Google APIs ARM 64 v8a
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6821437
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_271
    Python: 3.8.4
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

## 预期结果
- 实现android的自动链接

**Comment by sunnylqm** [comment]
这你得自己去读cli的源码研究了

**Comment by 322455116** [comment]
- 感谢回答.  
 - 修改的位置应该是react-native/react-native.config.js里. 根据官方文档, platforms.android.sourceDir  的默认值为'./android',但是我没有修改成功.留个印记,作为参考.
![image](https://user-images.githubusercontent.com/50320468/111927316-438a0b00-8aeb-11eb-862a-95b9f8f0660e.png)
