### ISSUE TITLE
mac m1 ios 模拟器运行报错error: ReferenceError: SHA-1 for file 

### ISSUE THREAD

**Issue by FYZJFFY** [reactnativecn/react-native-website#508]
## 环境/版本信息
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 18.69 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 2021.09.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## 报错信息
error: ReferenceError: SHA-1 for file /Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js (/Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
    at DependencyGraph.getSha1 (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:245:13)
    at Transformer.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/Transformer.js:104:23)
    at Bundler.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/Bundler.js:48:30)
    at async Object.transform (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:101:12)
    at async processModule (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
    at async traverseDependenciesForSingleFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
    at async DeltaCalculator._getChangedDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
    at async DeltaCalculator.getDelta (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
undefined

## 红屏截图
![image](https://user-images.githubusercontent.com/49120215/133881725-2e5e506a-a95c-420f-ab5e-94e917927d78.png)

新手整了好几天了，网上没什么信息，救救孩子吧！！！

**Comment by sunnylqm** [comment]
新建好的项目？有做什么操作吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月18日(周六) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] mac m1 ios 模拟器运行报错error: ReferenceError: SHA-1 for file  (#508)




 
环境/版本信息
 
System:
 OS: macOS 11.5.2
 CPU: (8) x64 Apple M1
 Memory: 18.69 MB / 16.00 GB
 Shell: 5.8 - /bin/zsh
 Binaries:
 Node: 12.18.3 - /usr/local/bin/node
 Yarn: 1.22.5 - ~/.yarn/bin/yarn
 npm: 6.14.6 - /usr/local/bin/npm
 Watchman: 2021.09.06.00 - /opt/homebrew/bin/watchman
 Managers:
 CocoaPods: 1.11.2 - /usr/local/bin/pod
 SDKs:
 iOS SDK:
 Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
 Android SDK: Not Found
 IDEs:
 Android Studio: Not Found
 Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
 Languages:
 Java: Not Found
 npmPackages:
 @react-native-community/cli: Not Found
 react: 17.0.2 =&gt; 17.0.2
 react-native: 0.65.1 =&gt; 0.65.1
 react-native-macos: Not Found
 npmGlobalPackages:
 react-native: Not Found
 
报错信息
 
error: ReferenceError: SHA-1 for file /Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js (/Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js) is not computed.
 Potential causes:
 1) You have symlinks in your project - watchman does not follow symlinks.
 2) Check blockList in your metro.config.js and make sure it isn't excluding the file path.
 at DependencyGraph.getSha1 (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:245:13)
 at Transformer.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/Transformer.js:104:23)
 at Bundler.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/Bundler.js:48:30)
 at async Object.transform (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:101:12)
 at async processModule (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
 at async traverseDependenciesForSingleFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
 at async Promise.all (index 0)
 at async initialTraverseDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
 at async DeltaCalculator._getChangedDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
 at async DeltaCalculator.getDelta (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
 undefined
 
红屏截图
 

 
新手整了好几天了，网上没什么信息，救救孩子吧！！！

**Comment by FYZJFFY** [comment]
> 新建好的项目？有做什么操作吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年9月18日(周六) 下午4:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [reactnativecn/react-native-website] mac m1 ios 模拟器运行报错error: ReferenceError: SHA-1 for file (#508) 环境/版本信息 System: OS: macOS 11.5.2 CPU: (8) x64 Apple M1 Memory: 18.69 MB / 16.00 GB Shell: 5.8 - /bin/zsh Binaries: Node: 12.18.3 - /usr/local/bin/node Yarn: 1.22.5 - ~/.yarn/bin/yarn npm: 6.14.6 - /usr/local/bin/npm Watchman: 2021.09.06.00 - /opt/homebrew/bin/watchman Managers: CocoaPods: 1.11.2 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4 Android SDK: Not Found IDEs: Android Studio: Not Found Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild Languages: Java: Not Found npmPackages: @react-native-community/cli: Not Found react: 17.0.2 =&gt; 17.0.2 react-native: 0.65.1 =&gt; 0.65.1 react-native-macos: Not Found npmGlobalPackages: react-native: Not Found 报错信息 error: ReferenceError: SHA-1 for file /Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js (/Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js) is not computed. Potential causes: 1) You have symlinks in your project - watchman does not follow symlinks. 2) Check blockList in your metro.config.js and make sure it isn't excluding the file path. at DependencyGraph.getSha1 (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:245:13) at Transformer.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/Transformer.js:104:23) at Bundler.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/Bundler.js:48:30) at async Object.transform (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:101:12) at async processModule (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18) at async traverseDependenciesForSingleFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3) at async Promise.all (index 0) at async initialTraverseDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3) at async DeltaCalculator._getChangedDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25) at async DeltaCalculator.getDelta (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16) undefined 红屏截图 新手整了好几天了，网上没什么信息，救救孩子吧！！！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by FYZJFFY** [comment]
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年9月18日(周六) 下午4:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [reactnativecn/react-native-website] mac m1 ios 模拟器运行报错error: ReferenceError: SHA-1 for file (#508) 环境/版本信息

没什么操作的，就是根据文档一步一步来的，搭建的是完整原生环境
