### ISSUE TITLE
mac m1 ios 模拟器运行报错error: ReferenceError: SHA-1 for file #508

### ISSUE THREAD

**Issue by FYZJFFY** [reactnativecn/react-native-website#509]
## 环境/版本信息
System:
OS: macOS 11.5.2
CPU: (8) x64 Apple M1
Memory: 18.69 MB / 16.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 12.18.3 - /usr/local/bin/node
Yarn: 1.22.5 - ~/.yarn/bin/yarn
npm: 6.14.6 - /usr/local/bin/npm
Watchman: 2021.09.06.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
Languages:
Java: Not Found
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2 => 17.0.2
react-native: 0.65.1 => 0.65.1
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

## 报错信息
error: ReferenceError: SHA-1 for file /Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js (/Users/Freya/work/projects/AwesomeProject/node_modules/metro-runtime/src/polyfills/require.js) is not computed.
Potential causes:
1) You have symlinks in your project - watchman does not follow symlinks.
2) Check blockList in your metro.config.js and make sure it isn't excluding the file path.
at DependencyGraph.getSha1 (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:245:13)
at Transformer.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/Transformer.js:104:23)
at Bundler.transformFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/Bundler.js:48:30)
at async Object.transform (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:101:12)
at async processModule (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
at async traverseDependenciesForSingleFile (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
at async Promise.all (index 0)
at async initialTraverseDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
at async DeltaCalculator._getChangedDependencies (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
at async DeltaCalculator.getDelta (/Users/Freya/work/projects/AwesomeProject/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
undefined

## 红屏截图
![image](https://user-images.githubusercontent.com/49120215/133883319-30da17ee-9cdd-42d9-b6ff-53f247129b86.png)

新手整了好几天了，没做过什么操作，，就是根据文档一步一步来的，搭建的是完整原生环境。
网上没什么信息，救救孩子吧！！！

**Comment by Master-gg-02** [comment]
有没有在ios 文件夹下pod install

**Comment by Wang-yubo** [comment]
m1跑不起来 可以试试 以下两个命令：arch -arm64 yarn ios 或者 arch -arm64 npx react-native run-ios

**Comment by SharkCats** [comment]
我用intel处理器的Mac 跑也是报一模一样的错误
