### ISSUE TITLE
npm run android报错

### ISSUE THREAD

**Issue by happy1992** [reactnativecn/react-native-website#553]
请按以下格式提供问题的相关信息。

## 问题的具体描述
E:\Sofar\FrontEndCode\sofar_monitor_business_app>npm run android

> sofar_monitor_business_app@0.0.1 android E:\Sofar\FrontEndCode\sofar_monitor_business_app
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 863 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...
Downloading https://services.gradle.org/distributions/gradle-7.2-all.zip

Exception in thread "main" javax.net.ssl.SSLException: Connection reset
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
        at org.gradle.wrapper.Download.download(Download.java:67)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
        Suppressed: java.net.SocketException: Connection reset by peer: socket write error
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
                ... 19 more
Caused by: java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        ... 16 more

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Exception in thread "main" javax.net.ssl.SSLException: Connection reset
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
        at org.gradle.wrapper.Download.download(Download.java:67)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
        Suppressed: java.net.SocketException: Connection reset by peer: socket write error
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
                ... 19 more
Caused by: java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        ... 16 more

    at makeError (E:\Sofar\FrontEndCode\sofar_monitor_business_app\node_modules\execa\index.js:174:9)
    at E:\Sofar\FrontEndCode\sofar_monitor_business_app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (E:\Sofar\FrontEndCode\sofar_monitor_business_app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (E:\Sofar\FrontEndCode\sofar_monitor_business_app\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sofar_monitor_business_app@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sofar_monitor_business_app@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2022-01-21T13_40_26_069Z-debug.log

###环境
window
react-native版本：0.67.1
jdk11

###补充说明
运行npx react-native doctor，环境是正常的
E:\Sofar\FrontEndCode\sofar_monitor_business_app>npx react-native doctor
Common
 ✓ Node.js
 ✓ yarn

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

Errors:   0
Warnings: 0

**Comment by sunnylqm** [comment]
connection reset 标准翻墙问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月21日(周五) 晚上9:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] npm run android报错 (Issue #553)




 
请按以下格式提供问题的相关信息。
 
问题的具体描述
 
E:\Sofar\FrontEndCode\sofar_monitor_business_app&gt;npm run android
  
***@***.*** android E:\Sofar\FrontEndCode\sofar_monitor_business_app
 react-native run-android
  
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
 Jetifier found 863 file(s) to forward-jetify. Using 12 workers...
 info JS server already running.
 info Installing the app...
 Downloading https://services.gradle.org/distributions/gradle-7.2-all.zip
 
Exception in thread "main" javax.net.ssl.SSLException: Connection reset
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
 at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
 at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
 at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
 at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
 at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
 at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
 at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
 at org.gradle.wrapper.Download.download(Download.java:67)
 at org.gradle.wrapper.Install$1.call(Install.java:68)
 at org.gradle.wrapper.Install$1.call(Install.java:48)
 at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
 at org.gradle.wrapper.Install.createDist(Install.java:48)
 at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
 at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
 Suppressed: java.net.SocketException: Connection reset by peer: socket write error
 at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
 at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
 at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
 at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
 ... 19 more
 Caused by: java.net.SocketException: Connection reset
 at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
 at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
 at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
 at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
 ... 16 more
 
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
 Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
 Exception in thread "main" javax.net.ssl.SSLException: Connection reset
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
 at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
 at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
 at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
 at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
 at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
 at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
 at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
 at org.gradle.wrapper.Download.download(Download.java:67)
 at org.gradle.wrapper.Install$1.call(Install.java:68)
 at org.gradle.wrapper.Install$1.call(Install.java:48)
 at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
 at org.gradle.wrapper.Install.createDist(Install.java:48)
 at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
 at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
 Suppressed: java.net.SocketException: Connection reset by peer: socket write error
 at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
 at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
 at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
 at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
 ... 19 more
 Caused by: java.net.SocketException: Connection reset
 at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
 at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
 at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
 at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
 ... 16 more
 at makeError (E:\Sofar\FrontEndCode\sofar_monitor_business_app\node_modules\execa\index.js:174:9) at E:\Sofar\FrontEndCode\sofar_monitor_business_app\node_modules\execa\index.js:278:16 at processTicksAndRejections (internal/process/task_queues.js:95:5) at async runOnAllDevices ***@***.***\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5) at async Command.handleAction ***@***.***\cli\build\index.js:192:9)  
info Run CLI with --verbose flag for more details.
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! ***@***.*** android: react-native run-android
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the ***@***.*** android script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
 npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache_logs\2022-01-21T13_40_26_069Z-debug.log
 
###环境
 window
 react-native版本：0.67.1
 jdk11
 
###补充说明
 运行npx react-native doctor，环境是正常的
 E:\Sofar\FrontEndCode\sofar_monitor_business_app&gt;npx react-native doctor
 Common
 ✓ Node.js
 ✓ yarn
 
Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME
 
Errors:   0
 Warnings: 0
