### ISSUE TITLE
集成rn到原生Android项目  app崩溃报错（couldn't find DSO to load: libhermes.so）

### ISSUE THREAD

**Issue by 2689643380** [reactnativecn/react-native-website#690]
## 集成rn到原生Android项目  app崩溃报错（couldn't find DSO to load: libhermes.so）
BOARD=goldfish_x86
CPU_ABI2=
HOST=wpra9.hot.corp.google.com
versionName=3.7.0
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@dc244a3
CPU_ABI=x86
PERMISSIONS_REVIEW_REQUIRED=true
IS_USERDEBUG=false
DISPLAY=QSR1.190920.001
SUPPORTED_ABIS=[Ljava.lang.String;@5b313a0
FINGERPRINT=google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys
PRODUCT=sdk_gphone_x86
ID=QSR1.190920.001
TYPE=user
SERIAL=unknown
IS_CONTAINER=false
IS_ENG=false
DEVICE=generic_x86
TIME=1569042998000
IS_USER=true
MODEL=Android SDK built for x86
MANUFACTURER=Google
USER=android-build
versionCode=51
BRAND=google
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@2e95bd2
HARDWARE=ranchu
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=true
TAGS=release-keys
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/j9zz.android.vip/lib-main flags = 1]
	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/j9zz.android.vip-cKXXAVpffcdPHWLlmVJqPg==/lib/x86 flags = 0]
	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
	Native lib dir: /data/app/j9zz.android.vip-cKXXAVpffcdPHWLlmVJqPg==/lib/x86
 result: 0
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:25)
	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:369)
	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:316)
	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:94)
	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
	at j9zz.android.vip.engine.activity.SplashActivity.initRNCore(SplashActivity.java:106)
	at j9zz.android.vip.engine.activity.SplashActivity.onCreate(SplashActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:7802)
	at android.app.Activity.performCreate(Activity.java:7791)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by sunnylqm** [comment]
啥具体信息也没有（系统环境呢？版本呢？具体集成的代码呢？），我能做的只有给你算一卦
