### ISSUE TITLE
npx react-native init AwesomeProject Error message : Looks like your iOS environment is not properly set

### ISSUE THREAD

**Issue by yuanyixiaomei** [reactnativecn/react-native-website#691]
-When I configure the environment and run the following command
`npx react-native init AwesomeProject`

- Error message
```
An error occurred while installing json (2.6.3), and Bundler cannot continue.
Make sure that `gem install json -v '2.6.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.11.3, which depends on
    cocoapods-core was resolved to 1.11.3, which depends on
      algoliasearch was resolved to 1.27.5, which depends on
        json

✖ Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/opt/homebrew/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/init.js:129:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.initialize [as func] (/opt/homebrew/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/init.js:181:3)
    at async Command.handleAction (/opt/homebrew/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:106:9)
info Run CLI with --verbose flag for more details.
```

-Additional information
my Ruby version is :2.7.6
my Mac is :macOs Monterey 12.5.1
my Xcode is :14.2(14C18)
my pod is : 1.11.3

**Comment by sunnylqm** [comment]
有使用代理吗

**Comment by yuanyixiaomei** [comment]
> 
有用的公司的电脑，公司的网络是一直有代理的

**Comment by yuanyixiaomei** [comment]
npx react-native init tempProject --skip-install

cd tempProject

yarn install

cd ios

bundle install

bundle exec pod install

It works for me !!!
It should be that my company's computer blocked access to GitHub when it encountered the git hub URL.
