### ISSUE TITLE
[新手必读]RN环境搭建/入门学习的一些注意事项

### ISSUE THREAD

**Issue by sunnylqm** [reactnativecn/react-native-website#77]
#### 一切非官方博客、教程、讨论仅供参考，请始终以官方文档（请思考什么是官方？）为准

---

#### 请`避免`在用户名、目录名、文件名、变量名等处使用`中文、空格等特殊字符`。

工具链中任意一处对特殊字符处理不好就会导致莫名其妙且难以察觉的错误。不要挖这样的坑。请不要使用和核心模块同名的目录名（如`react`,`react-native`等，父目录也不行）。也请不要单独使用编程语言中常见的关键字作为目录名（如`class`, `native`, `new`, `package`等等）

---

#### 完整原生环境 VS 简易沙盒环境(CRNA / Expo)

`推荐配置完整原生环境`，虽然，比较麻烦😓
沙盒环境依赖于国外网络环境，不能直接发布应用，
也不能安装国内所常用的原生依赖库。不建议国内用户使用。

---

#### 我只有Windows电脑，可以同时编写两个平台的代码吗？

可以。RN代码在逻辑层上是直接复用的，只是在不同平台上编译不同的原生“壳子”。注意事项：
- 不要直接复制、移动项目，`务必使用git管理和分发项目`，不要上传`node_modules`目录。
- 不要使用仅支持单平台的组件。

---

#### 可以把代码移植到网页/小程序/……上吗？

官方并不直接支持其他平台。但github上可能有其他个人或组织提供了各种方案，
react-native-web, react-native-dom, reactXP, taro等等, 具体是否符合你的需求，需要你自己调研和评估。

---

####  推荐什么（免费）工具XX上网？

`所有工具其实都是免费公开下载的`，尽管其技术实现各有差异，但基本的原理都是依靠外面的服务器实现`代理上网`。然而服务器显然没有理由白白贡献给谁用，所谓的免费工具常常遭遇定时断开、限流、广告等也不难理解。要想获得稳定的网络，`自己购买服务器，自己（学习）搭建代理`是第一选择。`请仅用于学习工作，不要用于非法用途。`

---

#### 为什么我使用了工具，网页也能打开，还是安装失败？

代理工具本身都需要对系统的网络配置进行介入和修改。这一过程有的可以自动配置，有的不能，有的甚至需要特定的工具或者协议转换。所以不代表所有工具都能自动让所有程序稳定访问代理（常见的例子是有的工具默认对浏览器做了配置，但`命令行却没有生效`）。相关知识和配置请自行研究学习。

---

#### 关于版本选择

如果没有特殊需求，建立新项目`始终选择默认的最新版本`
  - RN仍然处于高速迭代中，并没有人建立全面的测试场景和标准，也没有人去做不同版本的评测，而官方基本只维护最新版本。

谨慎选择编译工具链版本
  - 所谓编译工具链是指JDK、Node、Xcode、Android Studio、Gradle、Python等编译RN时所依赖的底层工具，建议选择`文档所要求的最低版本`。

谨慎对待这些工具的更新提示，谨慎使用macOS的自动更新和brew的upgrade命令。如果不是相关领域的专家，请勿主动尝试新版本，尤其是大版本更新。

如果你的所有版本都符合文档要求，仍然遭遇错误，请不要犹豫，去issue区提出问题。

---

#### 请分辨可靠的信息来源

信息可靠度排序（同时请结合考虑版本、修改时间等因素）：
- Github官方仓库源码
- 官方网站文档、官方博客
- 官方网站文档翻译版
- Github官方仓库issue版块的讨论

——————以下资料来源，如果没有官方出处，`都不可靠`
- StackOverflow，专业论坛，博客， QQ群，贴吧，知道……

---

#### 请使用Markdown语法

请任意找一篇教程熟悉md语法，例如 https://www.jianshu.com/p/191d1e21f7ed
提问时，请`务必`将你的代码用markdown语法扩起来，否则格式紊乱，难以阅读。
最基本的用法就是用三个撇号（数字1键左边）上下把代码包起来，像下面这样

![f857e0c9-e558-42b5-a283-f7ac978d78f6-image](https://user-images.githubusercontent.com/615282/76585827-5a7e4080-651a-11ea-8d6f-025e321c26a3.png)

---

这样代码就会自动排版且带有语法高亮

**Comment by linzhiju007** [comment]
大佬们，搭建React Native一定要安装最新版的Node吗？

**Comment by sunnylqm** [comment]
@linzhiju007 
> 所谓编译工具链是指JDK、Node、Xcode、Android Studio、Gradle、Python等编译RN时所依赖的底层工具，建议选择文档所要求的最低版本。

**Comment by linzhiju007** [comment]
谢谢您的解答，因为我是初学者，不知道是否方便给我一些学习建议或者是学习方法的指导呢？谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sunny Luo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 下午4:26
收件人:&nbsp;"reactnativecn/react-native-website"<react-native-website@noreply.github.com&gt;;
抄送:&nbsp;"linzhiju007"<linzhiju007@163.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] [新手必读]RN环境搭建/入门学习的一些注意事项 (#77)





 
@linzhiju007
  
所谓编译工具链是指JDK、Node、Xcode、Android Studio、Gradle、Python等编译RN时所依赖的底层工具，建议选择文档所要求的最低版本。

**Comment by sunnylqm** [comment]
@linzhiju007 公开的建议就都在这里、网站上和之前的论坛里
此外可以考虑一对一的付费咨询

**Comment by linzhiju007** [comment]
好的，十分感谢您！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sunny Luo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 上午10:36
收件人:&nbsp;"reactnativecn/react-native-website"<react-native-website@noreply.github.com&gt;;
抄送:&nbsp;"linzhiju007"<linzhiju007@163.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] [新手必读]RN环境搭建/入门学习的一些注意事项 (#77)





 
公开的建议就都在这里、网站上和之前的论坛里
 此外可以考虑一对一的付费咨询

**Comment by sunmze** [comment]
PS E:\RNtest4\Demo2> yarn android
yarn run v1.22.4
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (E:\RNtest4\Demo2\node_modules\execa\index.js:174:9)
    at E:\RNtest4\Demo2\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (E:\RNtest4\Demo2\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (E:\RNtest4\Demo2\node_modules\@react-native-community\cli\build\index.js:186:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by xujinxing1996** [comment]
请问react-native start命令是做什么的？我应该什么时候用这个命令呢？

**Comment by sunmze** [comment]
你这个问题我建议你搭建好环境执行一下 你就知道了&nbsp; 再说了字面意思不清晰吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Venus"<notifications@github.com&gt;; 
发送时间: 2020年5月18日(星期一) 下午3:16
收件人: "reactnativecn/react-native-website"<react-native-website@noreply.github.com&gt;; 
抄送: "鱼儿"<515180748@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [reactnativecn/react-native-website] [新手必读]RN环境搭建/入门学习的一些注意事项 (#77)





 
请问react-native start命令是做什么的？我应该什么时候用这个命令呢？

**Comment by HelloWilliam** [comment]
第一次安装项目，在iOS里面执行```pod install```，卡住了是什么原因，墙的速度不够吗？
```
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.62.2)
Installing FBReactNativeSpec (0.62.2)
Installing Flipper (0.33.1)
```

**Comment by sunnylqm** [comment]
是的，cocoapods的这些包下载都很困难

**Comment by LassZhang** [comment]
@sunnylqm   cocoapods 这些包是不是需要科学上网 才能 pod install 成功

**Comment by LassZhang** [comment]
@HelloWilliam  最后怎么处理的，我的跟你一样，Pod install 很久

**Comment by LassZhang** [comment]
@HelloWilliam 这个是必需要 V科学上网 吧

**Comment by zhuhongyang** [comment]
rn 版本 0.62.2

**Comment by zhuhongyang** [comment]
rn 版本 0.62.2  创建导航栏  android  报错

**Comment by zhuhongyang** [comment]
rn 版本 0.62.2 创建导航栏
 android 报错  “RNCSafeAreaProvider” was not found in the UIManager
Web 正常

**Comment by wu1210787810** [comment]
我的build.gradle文件里镜像源换成了阿里的镜像源 可是用yarn android命令的时候提示阿里镜像源是https无法验证是怎么回事

**Comment by daidaic** [comment]
大佬，一直卡在这里。。也科学上网了。。是什么原因导致的。。
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.2)
Installing FBReactNativeSpec (0.63.2)
Installing Flipper (0.41.5)
Installing Flipper-DoubleConversion (1.1.7)
Installing Flipper-Folly (2.2.0)
Installing Flipper-Glog (0.3.6)
Installing Flipper-PeerTalk (0.0.4)
Installing Flipper-RSocket (1.1.0)
Installing FlipperKit (0.41.5)

**Comment by sunnylqm** [comment]
说明还不够科学

**Comment by fupan1018** [comment]
看了这个说明，估计坑特别多

**Comment by sunnylqm** [comment]
@fupan1018 这个说明适用于任何框架做app开发

**Comment by fengwei6666** [comment]
科学上网了，YouTube Google 都挺流畅的，但是这里还是一直失败，求教
user@userdeMacBook-Pro-3 ios % pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.3)
Installing FBReactNativeSpec (0.63.3)
Installing Flipper (0.54.0)
Installing Flipper-DoubleConversion (1.1.7)
Installing Flipper-Folly (2.2.0)
Installing Flipper-Glog (0.3.6)
[!] /bin/bash -c
set -e

**Comment by sunnylqm** [comment]
@fengwei6666 浏览器能用不代表命令行能用

**Comment by wen81643956** [comment]
> 科学上网了，YouTube Google 都挺流畅的，但是这里还是一直失败，求教
> user@userdeMacBook-Pro-3 ios % pod install
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> Downloading dependencies
> Installing CocoaAsyncSocket (7.6.4)
> Installing CocoaLibEvent (1.0.0)
> Installing DoubleConversion (1.1.6)
> Installing FBLazyVector (0.63.3)
> Installing FBReactNativeSpec (0.63.3)
> Installing Flipper (0.54.0)
> Installing Flipper-DoubleConversion (1.1.7)
> Installing Flipper-Folly (2.2.0)
> Installing Flipper-Glog (0.3.6)
> [!] /bin/bash -c
> set -e

刚好遇到了这个问题，你可以试试通过设置terminal的http代理：
`% export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;`
然后再重新pod install

**Comment by XJIAL88** [comment]
mac 搭建照着官网搭建环境运行报错

**Comment by HugoChaan** [comment]
对于m1 的macbook在操作上有没有什么变化呢？build的时候会crash

**Comment by sunnylqm** [comment]
任何问题、报错，截图另开个帖子按格式详细说明
你说个报错，crash有什么用呢？等人上门看吗？

**Comment by yangyanqin11** [comment]
项目怎样实现滑动到一定的位置，进行顶部吸附效果

**Comment by sunwen0402** [comment]
使用kotlin构建的脚本 settings.gradle.kts ,无法解析 applyNativeModulesSettingsGradle(settings)  怎么解决啊?

**Comment by sunmze** [comment]
> 使用kotlin构建的脚本 settings.gradle.kts ,无法解析 applyNativeModulesSettingsGradle(settings) 怎么解决啊?

你这个是应该是gradle的版本不对导致的 ，先把gradle的版本对应上就ok了

**Comment by sunwen0402** [comment]
> > 使用kotlin构建的脚本settings.gradle.kts，无法解析applyNativeModulesSettingsGradle(settings) 怎么解决啊？
> 
> 你这个应该是gradle的版本不对导致的，先把gradle的版本对应上就ok了



> > 使用kotlin构建的脚本settings.gradle.kts，无法解析applyNativeModulesSettingsGradle(settings) 怎么解决啊？
> 
> 你应该是gradle的版本不对导致的，先把gradle的版本对应上就ok了

试了好几个版本都不行, 把.kts 去掉 换成groovy 编写是可以的

**Comment by SanpLee** [comment]
有没有指教怎么卡在 pod install 后怎么处理啊，新手学react-native 搭建环境劝退率这么高吗，开了vpn ，设置代理还是不行，
已经努力到这里了

➜  ios pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.66.3)
Installing FBReactNativeSpec (0.66.3)
Installing Flipper (0.99.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.1.7)

[!] Error installing Flipper-DoubleConversion
[!] /usr/bin/git clone https://github.com/priteshrnandgaonkar/double-conversion.git /var/folders/8f/fb9531_n3w5df7cjdknqchww0000gn/T/d20211207-14673-1e857vo --template= --single-branch --depth 1 --branch v3.1.7

Cloning into '/var/folders/8f/fb9531_n3w5df7cjdknqchww0000gn/T/d20211207-14673-1e857vo'...
fatal: unable to access 'https://github.com/priteshrnandgaonkar/double-conversion.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by dongfangmeng** [comment]
请问以下，AS可以运行新建的安卓项目，但是rn0.66无法运行，怎么解决呢？`

首先报错error Failed to launch emulator. Reason: Emulator exited before boot..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to la
unch.

然后是error Failed to install the app. Make sure you have the Android development environment s
et up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081      
:ReactNative:Unexpected empty result of running '[node, E:\react虚拟项目\native\test-proj
ect\rn0.66\AwesomeProject\node_modules\@react-native-community\cli\build\bin.js, config]'
 command.
:ReactNative:Running '[node, E:\react虚拟项目\native\test-project\rn0.66\AwesomeProject\n
ode_modules\@react-native-community\cli\build\bin.js, config]' command failed.

下面是关于终端的全部截图，希望前辈们指点一下

![微信图片_20220112092525](https://user-images.githubusercontent.com/67366263/149047480-72a62f07-9009-43d5-a0af-42bedd35bb07.png)

![微信图片_20220112092534](https://user-images.githubusercontent.com/67366263/149047513-a5be0768-80aa-45c8-aa3a-5e066d54fddb.png)

![微信图片_20220112092541](https://user-images.githubusercontent.com/67366263/149047529-cb430706-759f-446a-96e7-a1e2f7816f45.png)

**Comment by sunnylqm** [comment]
有几个问题，主要都在于你不看说明


首先，文档中和本帖子都明确说明，路径中不应该出现中文字符（它不一定会导致问题，但说不定什么情况下就会，而且非常不好排查问题）
其次，文档中也明确说明，使用as时不要升级gradle，而你仍然选择了升级
最后，截图中也说明了，由于你升级了gradle，所以它现在requires java 11，而你仍然没看见


你现在要么回退gradle版本，要么升级jdk版本，要么只用as运行（as自带需要的jdk版本）。但无论如何，希望你以后看清说明



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月12日(周三) 上午9:30
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] [新手必读]RN环境搭建/入门学习的一些注意事项 (#77)




 
请问以下，AS可以运行新建的安卓项目，但是rn0.66无法运行，怎么解决呢？`
 
首先报错error Failed to launch emulator. Reason: Emulator exited before boot..
 warn Please launch an emulator manually or connect a device. Otherwise app may fail to la
 unch.
 
然后是error Failed to install the app. Make sure you have the Android development environment s
 et up: https://reactnative.dev/docs/environment-setup.
 Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
 :ReactNative:Unexpected empty result of running '[node, E:\react虚拟项目\native\test-proj
 ***@***.***\cli\build\bin.js, config]'
 command.
 :ReactNative:Running '[node, E:\react虚拟项目\native\test-project\rn0.66\AwesomeProject\n
 ***@***.***\cli\build\bin.js, config]' command failed.
 
下面是关于终端的全部截图，希望前辈们指点一下

**Comment by dongfangmeng** [comment]
你好，我在别人电脑上试过了，路径没有中文字符，AS2020.3.1 for Windows 64-bit&nbsp;自带的gradle版本是7.0.2，然而rn默认的版本确是6.9，
rn不是要求jdk为8吗, 电脑上也是安的jdk8,所以我的问题点就是在gradle了吧，7.0.2需要java 11吗？ 我是应该卸载AS安装版本是6.9的AS吗？



无法启动

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reactnativecn/react-native-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 上午10:06
***@***.***&gt;;
抄送:&nbsp;"学徒   Φ  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] [新手必读]RN环境搭建/入门学习的一些注意事项 (#77)





 有几个问题，主要都在于你不看说明 
 
 
 首先，文档中和本帖子都明确说明，路径中不应该出现中文字符（它不一定会导致问题，但说不定什么情况下就会，而且非常不好排查问题） 
 其次，文档中也明确说明，使用as时不要升级gradle，而你仍然选择了升级 
 最后，截图中也说明了，由于你升级了gradle，所以它现在requires java 11，而你仍然没看见 
 
 
 你现在要么回退gradle版本，要么升级jdk版本，要么只用as运行（as自带需要的jdk版本）。但无论如何，希望你以后看清说明 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年1月12日(周三) 上午9:30 
 收件人: ***@***.***&amp;gt;; 
 抄送: "Sunny ***@***.******@***.***&amp;gt;; 
 主题: Re: [reactnativecn/react-native-website] [新手必读]RN环境搭建/入门学习的一些注意事项 (#77) 
 
 
 
 
   
 请问以下，AS可以运行新建的安卓项目，但是rn0.66无法运行，怎么解决呢？` 
   
 首先报错error Failed to launch emulator. Reason: Emulator exited before boot.. 
  warn Please launch an emulator manually or connect a device. Otherwise app may fail to la 
  unch. 
   
 然后是error Failed to install the app. Make sure you have the Android development environment s 
  et up: https://reactnative.dev/docs/environment-setup. 
  Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 
  :ReactNative:Unexpected empty result of running '[node, E:\react虚拟项目\native\test-proj 
  ***@***.***\cli\build\bin.js, config]' 
  command. 
  :ReactNative:Running '[node, E:\react虚拟项目\native\test-project\rn0.66\AwesomeProject\n 
  ***@***.***\cli\build\bin.js, config]' command failed. 
   
 下面是关于终端的全部截图，希望前辈们指点一下 
   
 
   
 
   
 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you were mentioned.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunnylqm** [comment]
@dongfangmeng 
1、有任何问题应该开新帖而不是在这里盖楼
2、as并不自带gradle，gradle是随项目走的，但高版本的as打开低版本的项目时会提示升级（只有你点了升级，gradle才会被升级，所以文档中有特别的说明）

![image](https://user-images.githubusercontent.com/615282/149062907-d465180a-1880-459e-95e3-42a808c23387.png)

3、rn目前自带的gradle在jdk8和jdk11应该都可以运行，但更早版本只能运行于jdk8，为了保证最广泛的兼容性，目前文档采取jdk8的说法（对于这种底层工具链，原则上使用最低的兼容版本），以避免给更多新手带来困惑。将来如果有升级，文档会有相应调整。但总之，结合文档、实际环境、报错提示，根据当前的实际需求做实际的调整，而不是刻舟求剑。

**Comment by ming-js** [comment]
楼主，有代理工具可以推荐一下吗？？？

**Comment by wanghe4096** [comment]
# 安装环境

如果不是在真机下运 行， 很容易就能搞定。 

但是，如果在真机环境下运行， 需要安装很多依赖工具。 

其中卡问题最多的一个地方就是一个叫cocoapods的工具。 

安装过程中， 由于国内被各种墙的原因， 导致从github下载依赖包时，总是会出现网络错误。 

解决方法：

```c
 增加git的代理配置， 这个代理配置用于配置翻墙代理。 这个代理服务器必须要能翻墙。

[http]
 15         proxy = socks5://127.0.0.1:18080
 16 [https]
 17         proxy = socks5://127.0.0.1:18080

```

用xcode打开项目时， 应该打开 文件名叫：“AwesomeProject.xcworkspace” , 而非“AwesomeProject.xcodeproj”

# 总结一下

1. 项目初始创建结束后

```c
 cd ～/AwesomeProject/ios
```

1. 编辑Podfile文件，第一行追加

```c
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
```

目的是用清华的镜像源

```c
$ cd ~/.cocoapods/repos 
$ pod repo remove master
$ git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git master
```

1. 安装cocoapods 依赖

```c
$ cd ～/AwesomeProject/ios
$ pod install
```

1. 由于国内墙的原因， 你可能无法下载各类依赖包， 配置你的git代理

```c
$ git config --global -e
```

我的代理服务器端口是18080，这个端口是你翻用的那个端口

```c
[http]
 15         proxy = socks5://127.0.0.1:18080
 16 [https]
 17         proxy = socks5://127.0.0.1:18080

```

1. 重新安装

```c
$ cd ~/AwesomeProject/ios
$ pod install
```

1. 打开名为AwesomeProject.AwesomeProject.xcworkspace， 注意这里不是AwesomeProject.xcodeproj
2. 配置appid授权

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/0868d7a6-f9a0-49dc-836e-9347aed854e9/Untitled.png)

1. 让podfile的ios版本和你设备的ios保持一致

**Comment by heitings** [comment]
各位大佬有没有什么成熟的框架推荐便于快速开发项目的？
