### ISSUE TITLE
RN项目在其他电脑上一直启动不起来

### ISSUE THREAD

**Issue by Aoyang1** [reactnativecn/react-native-website#781]
## 项目在其他电脑上一直启动不起来

- 使用 `yarn android` 报错下面错误
```js
> Task :expo-constants:createDebugExpoConfig FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
62 actionable tasks: 4 executed, 58 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-constants:createDebugExpoConfig'.
> Unable to delete file 'C:\test\dating-native\node_modules\expo-constants\android\build\generated\assets\expo-constants\debug'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 55s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-constants:createDebugExpoConfig'.
> Unable to delete file 'C:\test\dating-native\node_modules\expo-constants\android\build\generated\assets\expo-constants\debug'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 55s

    at makeError (C:\test\dating-native\node_modules\execa\index.js:174:9)
    at C:\test\dating-native\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\test\dating-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\test\dating-native\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

请问大佬们这个是什么问题，如何解决，

**Comment by sunnylqm** [comment]
> Unable to delete file 'C:\test\dating-native\node_modules\expo-constants\android\build\generated\assets\expo-constants\debug'

不知道为啥它删不掉这个文件，你帮它删下再跑试试咯
