### ISSUE TITLE
Error: Command failed with exit code 1: cmd.exe /C E:\lbk\rndemo\node_modules.bin\launchPackager.bat

### ISSUE THREAD

**Issue by Liangbaokun** [reactnativecn/react-native-website#782]
请按以下格式提供问题的相关信息。

## 问题的具体描述

- 从官网指示来跑的，运行不起来，刚入坑nr的小白不知道怎么这是哪里的问题，请大佬相助，非常感谢~
- info Opening app on Android...
Error: Command failed with exit code 1: cmd.exe /C E:\lbk\rndemo\node_modules\.bin\launchPackager.bat
    at makeError (E:\lbk\rndemo\node_modules\execa\lib\error.js:60:11)
    at handlePromise (E:\lbk\rndemo\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.runAndroid [as func] (E:\lbk\rndemo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:96:7)
    at async Command.handleAction (E:\lbk\rndemo\node_modules\@react-native-community\cli\build\index.js:118:9)
![image](https://github.com/reactnativecn/react-native-website/assets/52308901/1e3a6588-8cbf-4612-92e3-bd14ee3bbbf1)

- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
![image](https://github.com/reactnativecn/react-native-website/assets/52308901/85650fb2-f0f5-4c87-892a-4a93dc2ecc3f)
![image](https://github.com/reactnativecn/react-native-website/assets/52308901/c36b2b81-bec8-4932-8153-d2a549bc8181)

环境请看图
## 预期结果
这个应该构建运行成功

**Comment by Liangbaokun** [comment]
删过了node_modules ,重新yarn 安装之后也运行不起来

**Comment by sunnylqm** [comment]
环境信息呢

<img width="689" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/615282/1a3c8a14-130c-4e2f-a2f6-b783de9fbdae">
