### ISSUE TITLE
升级了react-native-update-cli之后，发布的更新包导致应用闪退

### ISSUE THREAD

**Issue by dompro** [reactnativecn/react-native-website#79]
按照往常的操作，执行操作：
`pushy bundle --platform android`
然后出现如下提示：
```
Error: 请升级cli后再尝试( npm i -g react-native-update-cli )
    at /node_modules/react-native-update/local-cli/lib/api.js:8:27
    at Generator.next (<anonymous>)
    at step (/node_modules/react-native-update/local-cli/lib/api.js:76:191)
    at /node_modules/react-native-update/local-cli/lib/api.js:76:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
于是按照提示，进行升级：
`npm i -g react-native-update-cli`
升级成功后，执行：
`pushy bundle --platform android`
像往常一样填写更新信息，然后进行升级测试
APP端也提示了升级，并且也下载成功，重新打开之后就闪退，之后再也打不开。

本次的代码调整非常少，应该不是自身代码引起的闪退，应该是升级了cli之后引起的，这种情况怎么处理？

**Comment by dompro** [comment]
使用的rn版本：v0.59.8
react-native-update：v5.5.6
react-native-update-cli：v1.0.8

在升级cli之前，一直可以正常热更新，热更新原包是去年8月份左右编译的。

这是闪退时的log：
```
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
                                                   Process: com.xxx, PID: 23597
                                                   com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.xxx/files/_update/s4W6jPfIaSKCxj3lhTyKDfY-LESl/index.bundlejs: No such file or directory
                                                       at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:224)
                                                       at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:52)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:247)
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1152)
                                                       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
                                                       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
                                                       at java.lang.Thread.run(Thread.java:929)

```

**Comment by sunnylqm** [comment]
和这个问题重复  https://github.com/reactnativecn/react-native-pushy/issues/313
但我们还不清楚具体原因
