### ISSUE TITLE
npx @react-native-community/cli@latest init 的时候TypeError: fetch failed

### ISSUE THREAD

**Issue by zhangweiyuan** [reactnativecn/react-native-website#902]
谁能帮忙看一下是什么原因啊，一直显示这个，vpn也开了。
zhangweiyuan@zhangweiyuandeMacBook-Air mhy-app-user % npx @react-native-community/cli@latest init mhyproject --verbose

debug We couldn't find a package.json in your project. Are you sure you are running it inside a React Native project?
debug Failed to load configuration of your project. Only a subset of commands will be available.
debug Mapped: latest -> 0.76.1
debug [template]: is '0.76.1 (0.76.1)' < '0.75.0' = no, look for template in @react-native-community/template
error fetch failed.
TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at async getTemplateVersion (/Users/zhangweiyuan/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/tools/npm.js:117:16)
    at async createTemplateUri (/Users/zhangweiyuan/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/version.js:53:29)
    at async createProject (/Users/zhangweiyuan/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:338:23)
    at async Object.initialize [as func] (/Users/zhangweiyuan/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:418:7)
    at async Command.handleAction (/Users/zhangweiyuan/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/index.js:116:9)
zhangweiyuan@zhangweiyuandeMacBook-Air mhy-app-user %

**Comment by 848398288** [comment]
一样 没搞懂是什么问题 我还以为是node版本太高，我还去降了个node到18也是不行
<img width="725" alt="1" src="https://github.com/user-attachments/assets/a45c58c1-b55a-4aff-9c08-a8e0b1c8d80d">

**Comment by HuXin957** [comment]
> 一样 没搞懂是什么问题 我还以为是node版本太高，我还去降了个node到18也是不行 <img alt="1" width="725" src="https://private-user-images.githubusercontent.com/67260394/383189664-a45c58c1-b55a-4aff-9c08-a8e0b1c8d80d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTAxNDgsIm5iZiI6MTczMTA0OTg0OCwicGF0aCI6Ii82NzI2MDM5NC8zODMxODk2NjQtYTQ1YzU4YzEtYjU1YS00YWZmLTljMDgtYThlMGIxYzhkODBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA3MTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZDg5N2YxZTRkMWVhYWFjMzFiNTMzM2E2YWUwY2NjODlkZTg0ZDkyOTBiNjQ0YzExMjc3ZjRkNjllODcxYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.33a9DwUyxkx8WFj7s8mizvNMpEySITn6ejJ46SdD4OM">

please retry!

**Comment by belikers** [comment]
网络问题，我也遇到了，多试几次就好了
